apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app

# the worker app has no Services listening
spec:
  containers:
    - name: worker-app
      image:  kodekloud/examplevotingapp_worker:v1
      
      
        
